# -*- coding: utf-8 -*-
"""Cifar100DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GH7NumUUGulHkkrTAegxngFzQrtzyHn7
"""

import tensorflow as tf
from tensorflow.keras.datasets import cifar100
import matplotlib.pyplot as plt
import numpy as np

(X_train,Y_train) , (X_test,Y_test) = cifar100.load_data()

X_train = X_train / 255
X_test = X_test / 255

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(32,32,3)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(100,activation='softmax')
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.fit(X_train,Y_train,epochs=30)

prediction = model.predict(X_test)

plt.imshow(X_test[100] , cmap="Blues")
plt.title("Predicted:" [np.argmax(prediction[100])])
plt.axis("off")
plt.show()

